import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CalendarDays, CarFront, Fuel, Gauge, LockKeyhole, MapPin, Settings2, ShieldCheck } from 'lucide-react';
import { vehiclesApi } from '../api/vehicles.api';
import { LoadingState, ErrorState, EmptyState } from '../components/StateView';
import { Badge } from '../components/Badge';
import { money, labelize } from '../utils/format';
import { useAuth } from '../contexts/AuthContext';
import type { Vehicle } from '../types/domain';

function placeholderPhoto(label = 'AutoStand') { const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#f8fafc"/><rect x="40" y="40" width="720" height="420" rx="28" fill="#e2e8f0"/><path d="M170 320h460l45 50H125l45-50Zm58-18 52-100c8-15 22-24 39-24h110c18 0 34 10 42 26l50 98H228Z" fill="#0f172a"/><circle cx="240" cy="382" r="34" fill="#334155"/><circle cx="560" cy="382" r="34" fill="#334155"/><text x="400" y="120" text-anchor="middle" font-family="Arial" font-size="28" font-weight="700" fill="#0f172a">${label}</text></svg>`; return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`; }
function getPhotos(vehicle: Vehicle): string[] { const source = [...(vehicle.photos || []), ...(vehicle.images || []), ...(vehicle.photoUrls || [])].filter(Boolean).slice(0, 8); return Array.from({ length: 8 }, (_, i) => source[i] || placeholderPhoto(`Foto ${i + 1}`)); }

export function CustomerCatalogPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const authenticatedCatalog = user?.role === 'CLIENTE';
  const load = () => { if (!authenticatedCatalog) return; setLoading(true); setError(''); vehiclesApi.list({ status: 'AVAILABLE', page: 1, limit: 20, search }).then((r) => setVehicles(r.data)).catch((e) => setError(e instanceof Error ? e.message : 'Não foi possível carregar as viaturas disponíveis.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [authenticatedCatalog, search]);

  if (!authenticatedCatalog) return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to="/" className="font-black">AutoStand</Link><Link to="/login" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Entrar</Link></div></header><main className="mx-auto max-w-3xl px-5 py-20 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-red-50 text-red-600"><LockKeyhole /></div><h1 className="mt-6 text-4xl font-black">Catálogo de veículos</h1><p className="mx-auto mt-4 max-w-2xl text-slate-500">O acesso aos veículos é protegido pela API do AutoStand. Entra com uma conta de cliente para consultar as viaturas disponíveis e as respetivas informações.</p><Link to="/login" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white">Entrar como cliente <ArrowRight size={17} /></Link></main></div>;

  return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><Link to="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-red-600 font-black text-white">A</div><div><div className="font-black">AutoStand</div><div className="text-xs text-slate-400">Portal do cliente</div></div></Link><button type="button" onClick={() => navigate('/login')} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Conta</button></div></header><main><section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-12"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full bg-red-50 px-3 py-1 text-xs font-bold uppercase tracking-wide text-red-700"><CarFront size={14} /> Veículos disponíveis</div><h1 className="mt-5 text-4xl font-black sm:text-5xl">Consulta o catálogo AutoStand.</h1><p className="mt-4 text-lg leading-8 text-slate-500">Pesquisa por marca, modelo ou matrícula e abre a ficha completa da viatura.</p></div><div className="mt-8 max-w-2xl"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Pesquisar por marca, modelo ou matrícula" className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3.5 outline-none focus:border-red-400 focus:bg-white" /></div></div></section><section className="mx-auto max-w-7xl px-5 py-10">{loading ? <LoadingState /> : error ? <ErrorState text={error} retry={load} /> : vehicles.length === 0 ? <EmptyState text="Nenhuma viatura disponível encontrada." /> : <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{vehicles.map((vehicle) => <CatalogCard key={vehicle.id} vehicle={vehicle} />)}</div>}</section></main></div>;
}

function CatalogCard({ vehicle }: { vehicle: Vehicle }) { const photo = getPhotos(vehicle)[0]; return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><img src={photo} alt={`${vehicle.brand} ${vehicle.model}`} className="h-60 w-full object-cover" /><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-black">{vehicle.brand} {vehicle.model}</p><p className="mt-1 text-sm text-slate-400">{vehicle.year} · {vehicle.plate}</p></div><Badge value="AVAILABLE" /></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm text-slate-500"><Stat icon={<Gauge size={15} />} text={vehicle.mileage ? `${vehicle.mileage.toLocaleString('pt-AO')} km` : '—'} /><Stat icon={<Fuel size={15} />} text={labelize(vehicle.fuel)} /><Stat icon={<Settings2 size={15} />} text={labelize(vehicle.transmission)} /><Stat icon={<MapPin size={15} />} text={vehicle.stand?.name || `Stand #${vehicle.standId}`} /></div><div className="mt-6 flex items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-slate-400">Preço</p><p className="mt-1 text-xl font-black">{money(vehicle.salePrice)}</p></div><Link to={`/portal/vehicles/${vehicle.id}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Ver detalhes <ArrowRight size={16} /></Link></div></div></article>; }
function Stat({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex min-w-0 items-center gap-2"><span className="text-slate-400">{icon}</span><span className="truncate">{text}</span></div>; }

export function CustomerVehicleDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const [vehicle, setVehicle] = useState<Vehicle | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [activePhoto, setActivePhoto] = useState(0);
  const authenticated = user?.role === 'CLIENTE';
  useEffect(() => { if (!authenticated) { setLoading(false); return; } setLoading(true); vehiclesApi.get(Number(id)).then(setVehicle).catch((e) => setError(e instanceof Error ? e.message : 'Não foi possível carregar a viatura.')).finally(() => setLoading(false)); }, [authenticated, id]);
  const photos = useMemo(() => vehicle ? getPhotos(vehicle) : [], [vehicle]);
  if (!authenticated) return <div className="grid min-h-screen place-items-center bg-slate-50 p-5"><div className="max-w-lg rounded-3xl border border-slate-200 bg-white p-8 text-center"><LockKeyhole className="mx-auto text-red-600" /><h1 className="mt-4 text-2xl font-black">Acesso reservado a clientes</h1><p className="mt-2 text-slate-500">Entra no portal do cliente para consultar os detalhes desta viatura.</p><Link to="/login" className="mt-6 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Entrar</Link></div></div>;
  if (loading) return <div className="min-h-screen bg-slate-50"><LoadingState /></div>; if (error || !vehicle) return <div className="min-h-screen bg-slate-50 p-5"><ErrorState text={error || 'Viatura não encontrada.'} retry={() => navigate('/portal')} /></div>;
  return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link to="/portal" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={17} /> Voltar</Link><span className="text-sm font-semibold">Portal do cliente</span></div></header><main className="mx-auto max-w-7xl px-5 py-8"><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><section><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><img src={photos[activePhoto]} alt={`${vehicle.brand} ${vehicle.model} - foto ${activePhoto + 1}`} className="aspect-[16/10] w-full object-cover" /></div><div className="mt-4 grid grid-cols-4 gap-3 sm:grid-cols-8">{photos.map((src, index) => <button key={`${src}-${index}`} type="button" onClick={() => setActivePhoto(index)} className={`overflow-hidden rounded-xl border-2 bg-white ${activePhoto === index ? 'border-red-600' : 'border-transparent'}`}><img src={src} alt={`Foto ${index + 1}`} className="aspect-square w-full object-cover" /></button>)}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-6 lg:p-8"><div className="flex items-center justify-between"><Badge value={vehicle.status} /><span className="text-sm text-slate-400">#{vehicle.id}</span></div><h1 className="mt-4 text-3xl font-black">{vehicle.brand} {vehicle.model}</h1><p className="mt-2 text-slate-500">{vehicle.description || 'Sem descrição.'}</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><DetailStat label="Ano" value={String(vehicle.year)} icon={<CalendarDays size={17} />} /><DetailStat label="Matrícula" value={vehicle.plate} icon={<CarFront size={17} />} /><DetailStat label="Quilometragem" value={vehicle.mileage ? `${vehicle.mileage.toLocaleString('pt-AO')} km` : '—'} icon={<Gauge size={17} />} /><DetailStat label="Combustível" value={labelize(vehicle.fuel)} icon={<Fuel size={17} />} /><DetailStat label="Transmissão" value={labelize(vehicle.transmission)} icon={<Settings2 size={17} />} /><DetailStat label="Cor" value={vehicle.color || '—'} icon={<CarFront size={17} />} /><DetailStat label="Stand" value={vehicle.stand?.name || `#${vehicle.standId}`} icon={<MapPin size={17} />} /><DetailStat label="VIN" value={vehicle.vin || '—'} icon={<ShieldCheck size={17} />} /></div><div className="mt-8 rounded-2xl bg-slate-50 p-5"><p className="text-xs uppercase tracking-wide text-slate-400">Preço de venda</p><p className="mt-1 text-3xl font-black">{money(vehicle.salePrice)}</p><p className="mt-2 text-sm text-slate-500">Diária de aluguer: {money(vehicle.rentalDailyRate)}</p></div></section></div></main></div>;
}
function DetailStat({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center gap-2 text-slate-400">{icon}<span className="text-xs uppercase tracking-wide">{label}</span></div><p className="mt-2 break-words text-sm font-bold text-slate-800">{value || '—'}</p></div>; }
