import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Check, CheckCircle2, X, RotateCcw, Ban } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { LoadingState, ErrorState } from '../components/StateView';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { Toast } from '../components/Toast';
import { money, date, labelize } from '../utils/format';
import { vehiclesApi } from '../api/vehicles.api';
import { clientsApi } from '../api/clients.api';
import { standsApi } from '../api/stands.api';
import { processesApi } from '../api/processes.api';
import { contractsApi } from '../api/contracts.api';
import { usersApi } from '../api/users.api';
import { transfersApi } from '../api/transfers.api';
import { useToast } from '../hooks/useToast';
import { useAuth } from '../contexts/AuthContext';
import { canApproveTransfer, canManageStand } from '../utils/permissions';

function Detail({ title, subtitle, children, back = '/dashboard' }: { title: string; subtitle?: string; children: React.ReactNode; back?: string }) {
  return <><PageHeader title={title} subtitle={subtitle} action={<button onClick={() => window.location.assign(back)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold"><ArrowLeft size={16} /> Voltar</button>} />{children}</>;
}
function Info({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-bold">{title}</h2><div className="divide-y divide-slate-100">{children}</div></div>; }
function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-center justify-between gap-4 py-3 text-sm"><span className="text-slate-400">{label}</span><span className="text-right font-medium text-slate-700">{value ?? '—'}</span></div>; }

export function VehicleDetailPage() {
  const { id } = useParams(); const [data, setData] = useState<any>(); const [error, setError] = useState('');
  const load = () => vehiclesApi.get(Number(id)).then(setData).catch((e) => setError(e instanceof Error ? e.message : 'Não foi possível carregar a viatura.'));
  useEffect(() => { load(); }, [id]);
  if (error) return <ErrorState text={error} retry={load} />; if (!data) return <LoadingState />;
  return <Detail title={`${data.brand} ${data.model}`} subtitle={`Viatura #${data.id}`} back="/vehicles"><div className="grid gap-6 lg:grid-cols-3"><Info title="Dados da viatura"><Row label="Matrícula" value={data.plate} /><Row label="VIN" value={data.vin} /><Row label="Ano" value={data.year} /><Row label="Cor" value={data.color} /><Row label="Combustível" value={labelize(data.fuel)} /><Row label="Transmissão" value={labelize(data.transmission)} /></Info><Info title="Operação"><Row label="Stand" value={data.stand?.name || data.standId} /><Row label="Estado" value={<Badge value={data.status} />} /><Row label="Quilometragem" value={data.mileage?.toLocaleString('pt-AO')} /><Row label="Preço venda" value={money(data.salePrice)} /><Row label="Diária aluguer" value={money(data.rentalDailyRate)} /></Info><Info title="Descrição"><p className="text-sm leading-6 text-slate-600">{data.description || 'Sem descrição.'}</p></Info></div></Detail>;
}

export function ClientDetailPage() { const { id } = useParams(); const [d, setD] = useState<any>(); const [e, setE] = useState(''); const load = () => clientsApi.get(Number(id)).then(setD).catch((x) => setE(x instanceof Error ? x.message : 'Não foi possível carregar o cliente.')); useEffect(() => { load(); }, [id]); if (e) return <ErrorState text={e} retry={load} />; if (!d) return <LoadingState />; return <Detail title={d.name} subtitle={`Cliente #${d.id}`} back="/clients"><div className="grid gap-6 md:grid-cols-2"><Info title="Dados pessoais"><Row label="Telefone" value={d.phone} /><Row label="Email" value={d.email} /><Row label="Documento" value={d.document} /><Row label="Endereço" value={d.address} /></Info><Info title="Resumo"><Row label="Processos" value={d.processesCount} /><Row label="Contratos" value={d.contractsCount} /></Info></div></Detail>; }

export function StandDetailPage() { const { id } = useParams(); const { user } = useAuth(); const [d, setD] = useState<any>(); const [e, setE] = useState(''); const toast = useToast(); const load = () => standsApi.get(Number(id)).then(setD).catch((x) => setE(x instanceof Error ? x.message : 'Não foi possível carregar o stand.')); useEffect(() => { load(); }, [id]); if (e) return <ErrorState text={e} retry={load} />; if (!d) return <LoadingState />; if (!canManageStand(user, d.id)) return <ErrorState text="Não tens acesso a este stand." />; return <Detail title={d.name} subtitle={`Stand #${d.id} · ${d.code}`} back="/stands"><div className="grid gap-6 md:grid-cols-2"><Info title="Informação"><Row label="Código" value={d.code} /><Row label="Telefone" value={d.phone} /><Row label="Endereço" value={d.address} /><Row label="Stand pai" value={d.parentStand?.name || d.parentStandId || 'Principal'} /><Row label="Estado" value={<Badge value={d.active === false ? 'INACTIVE' : 'ACTIVE'} />} /></Info><Info title="Indicadores"><Row label="Veículos" value={d.vehicleCount} /></Info></div><div className="mt-6 flex justify-end">{canManageStand(user, d.id) && <Link to={`/stands/${d.id}/edit`} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Gerir stand</Link>}</div>{toast.toast && <Toast message={toast.toast.message} type={toast.toast.type} onClose={toast.clear} />}</Detail>; }

export function GenericDetailPage({ kind }: { kind: 'process' | 'contract' | 'user' }) {
  const { id } = useParams(); const navigate = useNavigate(); const [d, setD] = useState<any>(); const [e, setE] = useState(''); const toast = useToast();
  const load = () => (kind === 'process' ? processesApi.get(Number(id)) : kind === 'contract' ? contractsApi.get(Number(id)) : usersApi.get(Number(id))).then(setD).catch((x) => setE(x instanceof Error ? x.message : 'Não foi possível carregar os dados.'));
  useEffect(() => { load(); }, [id, kind]); if (e) return <ErrorState text={e} retry={load} />; if (!d) return <LoadingState />;
  const cancelProcess = async () => { try { await processesApi.cancel(d.id); toast.success('Processo cancelado.'); await load(); } catch (x) { toast.error(x instanceof Error ? x.message : 'Não foi possível cancelar o processo.'); } };
  const back = kind === 'process' ? '/processes' : kind === 'contract' ? '/contracts' : '/users';
  return <Detail title={`${kind === 'process' ? 'Processo' : kind === 'contract' ? 'Contrato' : 'Utilizador'} #${d.id}`} subtitle={kind === 'user' ? d.email : labelize(d.type)} back={back}><div className="grid gap-6 lg:grid-cols-3"><Info title="Dados principais"><Row label="ID" value={d.id} /><Row label="Tipo" value={<Badge value={d.type || d.role} />} /><Row label="Estado" value={<Badge value={d.status || 'ACTIVE'} />} /><Row label="Stand" value={d.stand?.name || d.standId} /><Row label="Cliente" value={d.client?.name || d.clientId} /><Row label="Viatura" value={d.vehicle ? `${d.vehicle.brand} ${d.vehicle.model}` : d.vehicleId} /></Info>{kind === 'contract' && <Info title="Valores"><Row label="Total" value={money(d.totalAmount)} /><Row label="Entrada" value={money(d.downPayment)} /><Row label="Pago" value={money(d.amountPaid)} /><Row label="Saldo" value={money(d.balance)} /><Row label="Início" value={date(d.startDate)} /><Row label="Fim" value={date(d.endDate)} /></Info>}<Info title="Detalhes"><pre className="max-h-[500px] overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-300">{JSON.stringify(d, null, 2)}</pre></Info></div>{kind === 'process' && d.status === 'ACTIVE' && <div className="mt-6 flex flex-wrap justify-end gap-2"><Link to={`/contracts/${d.type === 'SALE' ? 'sale' : 'rental'}/new?processId=${d.id}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Criar contrato</Link><Button variant="danger" onClick={cancelProcess}><Ban size={16} /> Cancelar processo</Button></div>}{kind === 'contract' && d.type === 'RENTAL' && d.status === 'ACTIVE' && <div className="mt-6 flex justify-end"><Button onClick={() => navigate(`/rental-returns/new?contractId=${d.id}`)}><RotateCcw size={16} /> Registar devolução</Button></div>}{toast.toast && <Toast message={toast.toast.message} type={toast.toast.type} onClose={toast.clear} />}</Detail>;
}

export function TransferDetailPage() { const { id } = useParams(); const { user } = useAuth(); const [d, setD] = useState<any>(); const [e, setE] = useState(''); const toast = useToast(); const load = () => transfersApi.get(Number(id)).then(setD).catch((x) => setE(x instanceof Error ? x.message : 'Não foi possível carregar a transferência.')); useEffect(() => { load(); }, [id]); if (e) return <ErrorState text={e} retry={load} />; if (!d) return <LoadingState />; const act = async (fn: () => Promise<unknown>, msg: string) => { try { await fn(); toast.success(msg); await load(); } catch (x) { toast.error(x instanceof Error ? x.message : 'Operação não concluída.'); } }; const canApprove = canApproveTransfer(user); return <Detail title={`Transferência #${d.id}`} subtitle="Fluxo de aprovação entre stands" back="/transfers"><div className="space-y-6"><Info title="Transferência"><Row label="Viatura" value={d.vehicle ? `${d.vehicle.brand} ${d.vehicle.model}` : `#${d.vehicleId}`} /><Row label="Origem" value={d.fromStand?.name || d.fromStandId} /><Row label="Destino" value={d.toStand?.name || d.toStandId} /><Row label="Estado" value={<Badge value={d.status} />} /><Row label="Solicitada em" value={date(d.createdAt)} /></Info><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><FlowStep active={['PENDING','APPROVED','COMPLETED'].includes(d.status)} label="Solicitada" /><div className="h-px flex-1 bg-slate-200" /><FlowStep active={['APPROVED','COMPLETED'].includes(d.status)} label="Aprovada" /><div className="h-px flex-1 bg-slate-200" /><FlowStep active={d.status === 'COMPLETED'} label="Concluída" /></div><div className="mt-6 flex flex-wrap gap-2">{canApprove && d.status === 'PENDING' && <><Button onClick={() => act(() => transfersApi.approve(d.id), 'Transferência aprovada.')}><Check size={16} /> Aprovar</Button><Button variant="danger" onClick={() => act(() => transfersApi.reject(d.id, 'Rejeitada pelo administrador.'), 'Transferência rejeitada.')}><X size={16} /> Rejeitar</Button></>}{canApprove && d.status === 'APPROVED' && <Button onClick={() => act(() => transfersApi.complete(d.id), 'Transferência concluída.')}><CheckCircle2 size={16} /> Completar</Button>}</div></div>{toast.toast && <div />}</div></Detail>; }
function FlowStep({ active, label }: { active: boolean; label: string }) { return <div className={`flex items-center gap-2 text-xs font-semibold ${active ? 'text-slate-800' : 'text-slate-300'}`}><span className={`grid h-8 w-8 place-items-center rounded-full ${active ? 'bg-slate-950 text-white' : 'bg-slate-100'}`}>✓</span>{label}</div>; }
