import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { BarChart3, RefreshCw } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { Button } from '../components/Button';
import { ErrorState, LoadingState } from '../components/StateView';
import { reportsApi, type ReportQuery } from '../api/reports.api';
import { useAuth } from '../contexts/AuthContext';

const configs = { vehicles: { title: 'Relatório de viaturas', fn: 'vehicles' }, sales: { title: 'Relatório de vendas', fn: 'sales' }, rentals: { title: 'Relatório de alugueres', fn: 'rentals' }, receivables: { title: 'Valores a receber', fn: 'receivables' }, transfers: { title: 'Relatório de transferências', fn: 'transfers' } } as const;
export function ReportsIndex() { return <><PageHeader title="Relatórios" subtitle="Dados devolvidos diretamente pela API AutoStand" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(configs).map(([key, config]) => <Link key={key} to={`/reports/${key}`} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:border-slate-300"><BarChart3 className="text-red-600" /><h2 className="mt-4 font-bold">{config.title}</h2><p className="mt-1 text-sm text-slate-500">Consultar os dados do endpoint real.</p></Link>)}</div></>; }
export function ReportDetailPage() { const { type } = useParams(); const { user } = useAuth(); const config = configs[type as keyof typeof configs] || configs.vehicles; const [data, setData] = useState<unknown>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const query = useMemo<ReportQuery>(() => ({ from: from || undefined, to: to || undefined, standId: user?.standIds[0] }), [from, to, user?.standIds[0]]); const load = () => { if (from && to && from > to) { setError('A data inicial não pode ser posterior à data final.'); return; } setLoading(true); setError(''); (reportsApi[config.fn] as any)(query).then(setData).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Não foi possível carregar o relatório.')).finally(() => setLoading(false)); }; useEffect(load, [config.fn]); return <><PageHeader title={config.title} subtitle="Filtros suportados pela API: from, to e standId" action={<Button variant="secondary" onClick={load}><RefreshCw size={16} /> Atualizar</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-3"><input value={from} onChange={(e) => setFrom(e.target.value)} type="date" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm" /><input value={to} onChange={(e) => setTo(e.target.value)} type="date" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm" /><Button onClick={load}>Aplicar filtros</Button></div>{loading ? <LoadingState /> : error ? <ErrorState text={error} retry={load} /> : <pre className="max-h-[650px] overflow-auto rounded-2xl bg-slate-950 p-5 text-xs text-slate-200">{JSON.stringify(data, null, 2)}</pre>}</>; }
